### ISSUE TITLE
Update to jetty-9.4.x

### ISSUE THREAD

**Issue by gregw** [GoogleCloudPlatform/jetty-runtime#10]
This will provide access to:
- greatly improved session manager and gcloud/memcache integration
- more flexible request customizer
- improved performance

**Comment by gregw** [comment]
Progress report after testing again jetty-9.4.0.RC0:

- Update to latest version of `google-cloud-java` API. https://github.com/eclipse/jetty.project/issues/931

- We noticed a very large dependency tree of `google-cloud-java`  with duplicates and have opened https://github.com/GoogleCloudPlatform/google-cloud-java/issues/1278 to minimize this.   However, even when minimal, the dependency list will be too cumbersome to hide using Jetty's existing Black-list classpath, so we have opened https://github.com/eclipse/jetty.project/issues/963  to make hiding dependencies simpler.

- To achieve an initial "bug for bug" and backwards data compatibility the `gae-compat` session data store for `jetty-gae-compat-runtime` we need to expose a few more protected methods to avoid too duplicated code and create some modules for ease of configuration: https://github.com/eclipse/jetty.project/issues/941, https://github.com/eclipse/jetty.project/issues/944, https://github.com/eclipse/jetty.project/issues/945

- For the `jetty-runtime` data store session manager, it is currently not possible to programatically create the indexes that are needed for more efficient and correct session expiry. Thus we need to be able to run in a fallback mode that is less efficient if the indexes have not been created:  https://github.com/eclipse/jetty.project/issues/954

- It is unclear if versions deployed within the one gcloud project will be heterogeneous or homogeneous, so it is unclear how sessions should be partitioned (if at all).  For future flexibility we will add name space support: https://github.com/eclipse/jetty.project/issues/953

We are on track to implement most of these enhancements this week to produce a 9.4.0.RC1 next week, which we can again test integrate.

**Comment by jmcc0nn3ll** [comment]
@meltsufin can we consider this one closed now? master is on 9.4

**Comment by meltsufin** [comment]
@jmcc0nn3ll Yep, upgrade to 9.4 completed via #90 .
