### ISSUE TITLE
Avoid `chown -R` in Dockerfile

### ISSUE THREAD

**Issue by gregw** [GoogleCloudPlatform/jetty-runtime#11]
The use of `chown -R` in Dockerfiles is currently used to ensure the files are correctly owned.  However as pointed out in https://github.com/docker/docker/issues/6119, this can result in significant bloat in the size of the resulting docker images.

We should consider new docker features to avoid this issue https://github.com/docker/docker/pull/10775, or at least to a manual unpack of the tgz files that will allow user and group to be set correctly initially

**Comment by gregw** [comment]
Currently there is no good solution for this in docker.   Even explicitly doing the untar with a sudo command will waste disk space as the tar file will exist in a layer.   This issue needs to be reviewed once docker provides a solution for this.

**Comment by MaRuifeng** [comment]
So far as I have tested, the `chown` command does not introduce bloat in image size issue when the docker storage driver is _devicemapper_.

**Comment by mexpolk** [comment]
`RUN chown -R user:user` takes forever! And it does bloat the image size!
