### ISSUE TITLE
Add tests to verify X-Forwarded-Proto and X-Forwarded-For HTTP headers

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/jetty-runtime#112]
**X-Forwarded-Proto** - `HTTP` or `HTTPS` based on the origin request protocol. Will be interpreted by the `http-forwarded` customizer module.
**X-Forwarded-For** - a list of upstream proxy IP addresses in the form of:
`X-Forwarded-For: <client IP(s)>,<global forwarding rule IP>`. Will be interpreted by the `http-forwarded` customizer module.

**Comment by jmcc0nn3ll** [comment]
@RemoteOnly tests, suitable for test-war-smoke I would think
