### ISSUE TITLE
quickstart support?

### ISSUE THREAD

**Issue by gregw** [GoogleCloudPlatform/jetty-runtime#12]
Should quickstart be supported by default, or documented as a desirable feature.
Testing done in #8 using quickstart and/or annotations

**Comment by janbartel** [comment]
See issue #25 also.

**Comment by ludoch** [comment]
pure jetty-runtime does not have prebaked SDK support.
The user could modify her pom.xml to enable quickstart?

**Comment by gregw** [comment]
To use quickstart a user would need to: 
- add a quickstart-web.xml to WEB-INF
- enable the quickstart module on the jetty base.

Both are simple to do, so I think this is more a documentation/example issue rather than a coded feature.

**Comment by meltsufin** [comment]
Would they need to build a custom runtime to enable the quickstart module?

**Comment by gregw** [comment]
@meltsufin, yes they would need to provide their own Dockerfile that enables the quickstart module.

**Comment by joakime** [comment]
the regression testing could handle that in /jetty-runtime/ easily enough.

Each /tests/webapp/test-war-*/ has its own docker.

To do:
 - Add new test project
 - Dockerfile updated to add the quickstart module to the jetty.base
 - test-war-quickstart has maven plugin that builds out the quickstart-web.xml
 - deploy and integration testing as usual
