### ISSUE TITLE
Reuse docker-entrypoint.bash from openjdk:8 image

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/jetty-runtime#120]
Currently, we're overwriting the docker-entrypoint.bash file defined in the base image while duplicating most of the code in it. We should instead leverage the script in the base image. One option would be to define a different entrypoint script and call the one in the base image at the end after appending `$DEFAULT_ARGS` to `$JAVA_OPTS`.

**Comment by gregw** [comment]
I agree that it would be good not to duplicate the behaviour from the base entrypoint.  However, I'd rather not have an alternate entrypoint as it is pretty standard to use docker-entrypoint.bash and we want least surprise.

Instead, I would advocate having the base script start with something like:

```bash
#!/bin/bash

# source the supported feature JVM arguments
source /setup-env.bash
if [ -x /app-env.bash ] ; then
  source /app-env.bash
fi;
```

I believe all the subsequent difference in behaviour can be moved to such an app-env.bash script, but if not the changes needed in the base script should be minor to allow it to be more extensible.

Shall I prepare a PR along those lines?

**Comment by meltsufin** [comment]
Sure, this sounds good too.
