### ISSUE TITLE
Add logging documentation to README

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/jetty-runtime#122]
After merging #81

**Comment by gregw** [comment]
The PR #81 now includes documentation (Eg https://github.com/GoogleCloudPlatform/jetty-runtime/pull/81/commits/06b1a2e1e8f8a6627d9b40061651eedb8eafa7d0).

But will leave this open to trigger an extra review after the merge

**Comment by sparhomenko** [comment]
Thanks for the documentation guys, it really helped us to configure the logging in our GAE Flexible app. A small note: it recommends `WEB-INF/logging.properties` value for users that want to package `logging.properties` in their WAR. This didn't work for us as `Dockerfile` sets the current directory to `$JETTY_BASE`, not `$JETTY_BASE/webapps/root`. Changing the value to `webapps/root/WEB-INF/logging.properties` (we would prefer an absolute path, but doesn't look like `$JETTY_BASE` works in `app.yaml`) did the trick.

**Comment by meltsufin** [comment]
Glad the logging instructions helped you! Thanks for the note about `WEB-INF/logging.properties` not working, but I believe it's because we haven't released the new runtime with the changes from #81 yet. The update to `gcr.io/google-appengine/jetty` is coming next week.
