### ISSUE TITLE
Bypassing start.jar during quickstart

### ISSUE THREAD

**Issue by cassand** [GoogleCloudPlatform/jetty-runtime#171]
It might be interesting to bypass the start.jar mechanisms when quickstart is enabled. However for users extending the image this would implies changing the command to start Jetty.  

There is a possibility to reuse the command to generate the classpath during quickstart (start.jar --dry-run).

Related to: #170

**Comment by joakime** [comment]
Since PR #170 was merged, can this be considered closed now?
