### ISSUE TITLE
Documentation for Dockerfile enables jmx and hawtio console

### ISSUE THREAD

**Issue by gregw** [GoogleCloudPlatform/jetty-runtime#18]
The documentation for using a Dockerfile at https://cloud.google.com/appengine/docs/flexible/java/dev-jetty9  includes the modules to enable jmx and the hawtio console.  This should not be deployed by default as it has no authentication and allows anybody to access and control the server via JMX.

note also that the documentation is out of date and it does not indicate a docker director is needed.

**Comment by meltsufin** [comment]
The documentation is indeed out of date, but we shouldn't track that here.
In any case, the modules can be now enabled via the `JETTY_MODULES_ENABLE` environment variable.
