### ISSUE TITLE
Upgrade to the latest google-cloud-logging library

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/jetty-runtime#221]
We also should start using the Google Cloud Java BOM for managing library versions from Google Cloud Java.

Potential solution to #217.

**Comment by ChengyuanZhao** [comment]
The BOM for google cloud java includes many things we don't currently explicitly import in the jetty9-base pom.xml (which is then used throughout the rest of this repo): https://github.com/GoogleCloudPlatform/google-cloud-java/tree/master/google-cloud-bom

I assume we definitely don't want to manage a list of things to exclude from the BOM, right ? I think that adds an amount of annoyance that outweighs the benefits.

**Comment by meltsufin** [comment]
The BOM only has versions for dependencies. It shouldn't actually bring in any of the dependencies.
