### ISSUE TITLE
TraceLoggingEnhancer.setCurrentTraceId is not in correctly formatted.

### ISSUE THREAD

**Issue by bmenasha** [GoogleCloudPlatform/jetty-runtime#243]
The class  RequestContextScope.java class  is not formatting the traceId correctly.  According to the javadoc the TraceLoggingEnhancer.setCurrentTraceId expects  projects/[PROJECT_ID]/traces/[TRACE_ID], while we are just supplying [TRACE_ID]  within https://github.com/GoogleCloudPlatform/jetty-runtime/blob/master/jetty9-base/src/main/java/com/google/cloud/runtimes/jetty9/RequestContextScope.java

This was changed in the logging library with this pull request: 

https://github.com/googleapis/google-cloud-java/pull/3301

For more information see this blog post: https://cloud.google.com/blog/products/gcp/viewing-trace-spans-and-request-logs-in-multi-project-deployments

Thanks

**Comment by bmenasha** [comment]
Thank you very much for the fix Greg!  
Do you have any idea when it will be available in the production App Engine Flexible images we deploy?

**Comment by gregw** [comment]
@bmenasha I'm having some issues with testing a custom image, sop hopefully once they are sorted it will be good to go.

**Comment by joakime** [comment]
PR #244 has been merged, can this issue be closed?
