### ISSUE TITLE
Add test webapp module for quickstart

### ISSUE THREAD

**Issue by joakime** [GoogleCloudPlatform/jetty-runtime#25]
Create a `/tests/test-war-quickstart` that tests the quickstart facility of jetty.

The sample project should be sufficiently complex.   Perhaps either the spring petclinic, or the cdi/weld petclinic.

**Comment by joakime** [comment]
Since the existing spring petclinic is broken (due to Dandelion bug) we'll have to build our own spring petclinic.

We could include a known slow (to scan) jar file `org.webjars:extjs:5.1.0.jar` to be sure that the quickstart actually works.

I think we'll have to dig into the logs to test if this startup was truly "quick" or not.

**Comment by joakime** [comment]
Issue #33 is also a spring petclinic testcase (non-quickstart version)

**Comment by janbartel** [comment]
I think this is only useful to test if the gcloud sdk offers quickstart as an option during the deploy step. Is this the case @meltsufin or @aslo ?

**Comment by gregw** [comment]
As quickstart support is not directly supported by the SDK, let's close this one for now.
