### ISSUE TITLE
Create a test webapp for Session configurations

### ISSUE THREAD

**Issue by joakime** [GoogleCloudPlatform/jetty-runtime#26]
Identified sample test webapps:

 - Sessions using HashSessionManager
 - Sessions using jetty-gcloud-session-manager
  * include positive results with a sufficient cluster 
  * include negative results when using insufficient cluster size

**Comment by gregw** [comment]
I don't there is much value in testing hashsessionmanager, as we test that in pure jetty and it is not applicable to gcloud.   Sessions tests should test sessions that need gcloud services:
- default (memcache + datastore)
- datastore only
- sql session store

**Comment by joakime** [comment]
In other words, same webapp, same ITCase's, just different app.yaml (or jetty.base) configurations?

**Comment by gregw** [comment]
exactly - same web app, different app.yaml and maybe an extra xml or properties file in jetty.base.     We would also have to provision a gcloud SQL service.  This could be a once off or for all tests...   We will need this capability to do better testing of compat as well

**Comment by janbartel** [comment]
At least some part of issue #15 seems related to this one.
