### ISSUE TITLE
Create test webapps for bytecode scanning concerns

### ISSUE THREAD

**Issue by joakime** [GoogleCloudPlatform/jetty-runtime#29]
Identified behaviors to look for

 - Add individual `WEB-INF/lib/*.jar` for each bytecode support level 1.1 to 1.8
 - Add known common bad bytecode - (eg: `icu4j-2.6.1.jar` and the `com/ibm/icu/impl/data/LocaleElements_zh__PINYIN.class` entry)
 - Add known slow to scan jars - (eg: `org.webjars:extjs:5.1.0.jar`)
 - Include java 1.8 new bytecode (lamdas, etc)
 - Add webapp usage of an old asm.jar (to ensure that the server side will not fail with this setup)

**Comment by janbartel** [comment]
I can see that we might want to test compatibility of the asm version with various jdk bytecode, but not sure about the other tests:  we have the ability to set up jar include/exclude patterns to prevent scanning of bad/slow jars. So are we really just testing if the patterns work?

Also wrt asm.jar, what is really being tested here are server/system classes configurations, so should be a different test.

**Comment by meltsufin** [comment]
I'm not sure I understand which aspects of our runtime code this would be testing.
