### ISSUE TITLE
Create test webapps for JSP support levels

### ISSUE THREAD

**Issue by joakime** [GoogleCloudPlatform/jetty-runtime#31]
Identified webapps

 - JSP 2.0 very old usage
 - JSP 2.1 older usages
 - JSP 2.2 (seen in Jetty 8)
 - JSP 2.3 (seen in Jetty 9)
 - Custom Taglibs 
 - JSTL / EL usages
 - WEB-INF/lib/*.jar inclusions that can cause problems
   * extra javax.el (duplicates or more than 1 versions) api libs
   * extra javax.el (duplicates or more than 1 versions) impl libs
   * extra jstl (duplicates or more than 1 versions) api libs
   * extra jstl (duplicates or more than 1 versions) impl llibs

**Comment by joakime** [comment]
@janbartel can `WEB-INF/lib/` extras like fragments or resources include JSP files that can be used?

**Comment by joakime** [comment]
Also test partial JSP precompiled

**Comment by joakime** [comment]
Should also include test webapps that use older JSTL support versions.

 - JSTL 1.0
 - JSTL 1.1
 - JSTL 1.2

**Comment by janbartel** [comment]
@joakime these seem more like tests of jetty itself, rather than than testing the touchpoints with the google environment.

**Comment by meltsufin** [comment]
I agree with Jan that we should be careful not to focus on exhaustively testing Jetty itself, as that testing lives with the Jetty project. However, I do think we need a few test webapps that use different versions of JEE and the corresponding verisons of the the Servlet API/JSP/JST. I think the following 2 simple apps would be appropriate to test a bunch of things at once:
- JEE6 (Serlvet 3.0 / JSF 2.0 / EL 2.2 / JSP 2.2 / JSTL 1.2)
- JEE7 (Serlvet 3.1 / JSF 2.2 / EL 3.0 / JSP 2.3 / JSTL 1.2)

I'm not sure how many people are on older JEE versions, but this should cover the majority.

**Comment by joakime** [comment]
JSF is not part of Jetty, and we don't have a module for it either.

Typical use is to have the JSF components and libs be part of the webapp itself.

The nearest we can do (in the short term) with JSF is to grab one of the CDI/Weld test projects that use JSF from issue #36
