### ISSUE TITLE
Create test webapps for various servlet support levels

### ISSUE THREAD

**Issue by joakime** [GoogleCloudPlatform/jetty-runtime#32]
Some identified webapps

 - Servlet 2.3
 - Servlet 2.4
 - Servlet 2.5
 - Servlet 3.0 (w/ annotations, and async context)
 - Servlet 3.1 (w/ async I/O)
  * WEB-INF/lib resource manifests
  * WEB-INF/lib fragments

**Comment by janbartel** [comment]
@joakime  the jetty [test-servlet-spec webapp](https://github.com/eclipse/jetty.project/tree/jetty-9.4.x/tests/test-webapps/test-servlet-spec) can be used to test the servlet 3.0/3.1 features such as annotations, webfragments, meta-inf resources, programmatic configuration, custom ServletContainerInitializers etc. 

Currently none of the test webapps are released to maven central, but we could change that.

**Comment by joakime** [comment]
Should have tests for JNDI with these too.

**Comment by meltsufin** [comment]
I think JNDI is a great test case to have, since it's a unique capability of the Flexible runtime. I think we can collapse these into fewer test webapps if they're at the JEE support level. See #31 for a related discussion on JSP support levels.
