### ISSUE TITLE
Create test webapp for jersey / JAX-RS support

### ISSUE THREAD

**Issue by joakime** [GoogleCloudPlatform/jetty-runtime#34]
Jersey is a common toolkit seen with Jetty.

We should create a webapp showing setup and proper behavior of Jersey.

 - Should include problematic annotations (like `@Resource`)

**Comment by meltsufin** [comment]
Would this just be a test of Jetty not the runtime?

**Comment by jmcc0nn3ll** [comment]
This would be an environmental test, and the runtime is the environment.  IE We are not testing that it works in Jetty under whatever configuration...but does this work out of the box on the runtime itself.
