### ISSUE TITLE
Create test webapp for CDI/Weld

### ISSUE THREAD

**Issue by joakime** [GoogleCloudPlatform/jetty-runtime#36]
There are a number of weld maintained examples at

https://github.com/weld/core/tree/master/examples

I propose we use [weld's jsf/permalink example](https://github.com/weld/core/tree/master/examples/jsf/permalink)

**Comment by meltsufin** [comment]
@joakime Is this more of Jetty server test than the image?

**Comment by meltsufin** [comment]
weld module is not supported in the image
