### ISSUE TITLE
Create test webapp for native / JNI executions

### ISSUE THREAD

**Issue by joakime** [GoogleCloudPlatform/jetty-runtime#37]
If gcloud deployment allow for native / JNI executions then we should create a test webapp to ensure that works.

This could include a combination of using pre-existing binaries on the docker images, and also using libs included in the webapp.

**Comment by joakime** [comment]
Would include executing shellscripts from the webapp also under this category of testcases.

**Comment by meltsufin** [comment]
Yes, this is a good one, since one of the goals of Flexible runtimes is to allow JNI.
