### ISSUE TITLE
Where do we put tests that use jetty, but not jetty-runtime?

### ISSUE THREAD

**Issue by joakime** [GoogleCloudPlatform/jetty-runtime#38]
There's a few scenarios where Jetty is in use, but wouldn't use the jetty-runtime (or jetty-distribution) to execute.

A few common examples:

 * Solr
 * Spring-Boot
 * Dropwizard

**Comment by joakime** [comment]
You could add jetty booted via an OSGi container as another example

**Comment by gregw** [comment]
I don't think we need to test jetty per-se in these scenarios.  We just need to test the capabilities of the runtime.   So in this case such applications would likely be based on the openjdk-runtime.     We need tests at that level to check the capabilities the runtime provides: JRE, logging, cloud debugger, memcache, etc.

Having some 3rd party sample jars to test would not hurt either.

**Comment by joakime** [comment]
for low hanging fruit, Solr is an easy one then.

its pretty much an unpack, configure, and run setup.

**Comment by meltsufin** [comment]
I'm with @gregw that jetty-specific tests should not be in this repo. Closing.
