### ISSUE TITLE
Create test webapp with scala use

### ISSUE THREAD

**Issue by joakime** [GoogleCloudPlatform/jetty-runtime#39]
Do we want to have a test webapp showing scala behavior and usage with jetty-runtime?

**Comment by aslo** [comment]
I'd consider that to be a valid use case, but extremely low priority.

**Comment by joakime** [comment]
removed the question tag.  do we want to have a low priority tag?

**Comment by aslo** [comment]
Sounds good to me. I'll also create a high priority tag as well.

**Comment by meltsufin** [comment]
@joakime @aslo What aspects of the runtime would this be testing? Would this just be for documentation purposes?
