### ISSUE TITLE
Session Management backed by Memcache & Datastore

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/jetty-runtime#42]
Should be preceded by #41 that enables clustered session management using Datastore.
This feature should be optionally turned on using an environment variable.

**Comment by janbartel** [comment]
Depends on update to jetty-9.4 #10.

**Comment by janbartel** [comment]
Blocked by gcloud-datastore issue [149](https://github.com/GoogleCloudPlatform/google-cloud-datastore/issues/149).

**Comment by meltsufin** [comment]
Was done a while ago, minus the Memcache layer.
