### ISSUE TITLE
Create test webapp for JMX features?

### ISSUE THREAD

**Issue by joakime** [GoogleCloudPlatform/jetty-runtime#43]
How does JMX fit into the picture of testcases?

**Comment by gregw** [comment]
Currently there is no gcloud support for JMX that I know of (although it would be a good feature for the console).

Thus currently I don't think JMX needs to feature at all in our testing.   Rather it would be a good example to show how to configure JMX so it can remotely be accessed either by an embedded web console (eg hawtio) or by opening up a secured RMI port.
