### ISSUE TITLE
HttpUrlUtil should have ability to wait for server start

### ISSUE THREAD

**Issue by joakime** [GoogleCloudPlatform/jetty-runtime#48]
As there can be a delay between deploy and the webapp being available for traffic, the HttpURLUtil should have retry logic to keep retrying (for a little while) in case the startup is slow.

**Comment by jmcc0nn3ll** [comment]
codified the startup mechanism into a shared base class for all tests to extend as part of work on #103, since this class is a utility for testing the server should be available by the time it is used
