### ISSUE TITLE
Jetty module activation

### ISSUE THREAD

**Issue by gregw** [GoogleCloudPlatform/jetty-runtime#50]
The various features of jetty are activated and configured by our module mechanism, which has so far been done within the docker file.   There is a discussion about using environment variables to control some of these features, so this issue is to discuss exactly how that can be done.

Firstly some background on the jetty module mechanism.  An example is to activate gcloud sessions we need to run a command (currently from a Dockerfile RUN command) like:

```
java -jar $JETTY_HOME/start.jar --add-to-start=session-store-gcloud,jcl
```

The `--add-to-start` command enables both the `session-store-gcloud` module and it's dependencies, which primarily is the `sessions` module. Note that we also add the `jcl` module to pick one of our available implementations of java commons logging, which is a dependency of the gcloud library used (if there was only one, we'd pick it automatically).

To add memcache, you would need to run the command (or add it to the previous command):

```
java -jar $JETTY_HOME/start.jar --add-to-start=session-store-cache
```

This is easy enough to do in custom Dockerfiles, but the suggestion is that such features need to be selectable at run time via env variables.    So we need to consider how best to do that, so let's see what our `--add-to-start` command does.

When adding a thirdparty module like gcloud session, the `--add-to-start` command downloads any dependencies not part of the normal jetty distribution, which for gcloud, this is quiet a few jars, so I don't think we'd want to be doing this for every instance we start up as it increases the chance of a failure.      The solution to this is that in our image Dockerfile for `jetty-runtime` we can enable all the modules that might be enabled by env variables, so the library downloads are done, and then disable them by removing the related `start.d/*.ini` files.

Next the default command line is modified to include activation of the module, which is simply adding something like: `--module=session-store-gcloud` to the command line.     This is what could be done by a start script that checks the env variables.

Finally, the `--add-to-start` command creates a `start.d/session-store-gcloud.ini` file with parameters that can be configured for the module.  e.g.:

```
[] cat start.d/session-store-gcloud.ini 
# --------------------------------------- 
# Module: session-store-gcloud
# Enables GCloudDatastore session management.
# --------------------------------------- 
--module=session-store-gcloud


## GCloudDatastore Session config
#jetty.session.gcloud.maxRetries=5
#jetty.session.gcloud.backoffMs=1000



[] cat start.d/sessions.ini 
# --------------------------------------- 
# Module: sessions
# The session management. By enabling this module, it allows
# session management to be configured via the ini templates
# created or by enabling other session-cache or session-store
# modules.  Without this module enabled, the server may still
# use sessions, but their management cannot be configured.
# --------------------------------------- 
--module=sessions

## The name to uniquely identify this server instance
#jetty.sessionIdManager.workerName=node1

## Period between runs of the session scavenger (in seconds)
#jetty.sessionScavengeInterval.seconds=60

[] cat start.d/session-store-cache.ini 
# --------------------------------------- 
# Module: session-store-cache
# Enables caching of SessionData in front of a SessionDataStore.
# --------------------------------------- 
--module=session-store-cache


## Session Data Cache type: xmemcached
session-data-cache=xmemcached
#jetty.session.memcached.host=localhost
#jetty.session.memcached.port=11211
#jetty.session.memcached.expirySec=

```

As you can see, almost all the parameters are commented out, so the default settings are normally good.   This means that we can access the default module configuration simply by a start script that adds the appropriate `--module=` args to the command line based on the environment variables.

However, as soon as a user wants to configure any of these features, they are going to have to re-create the ini files and edit the parameters in them in their own custom Dockerfile.       This then creates a duality where a module might be enabled in either a `start.d/*.ini` file and/or enabled by the start script adding a command line argument based on an environment variable.

I don't think this duality is good and it will confuse many that the mechanism changes the moment they go from a default image to a custom image.

So another idea is that our Dockerfile can enable all the possible modules and then move their `start.d/*.ini` files to a `gae.d/` directory.    The start script would then check the env variables and if a feature is turned on, it would move the ini file(s) from `gae.d/` back to `start.d/`.     To configure these features they could then use a custom Dockerfile simply to replace/edit the `gae.d/*.ini` files that the start script would use.    Still not perfect but better.

Perhaps a better way would be for the start script to first check if a feature is already enabled, and if so ignore the env variables.  Note that jetty will throw an exception if you try to configure two contradictory modules (eg two non compatible session data stores), so if a user enables one session store and the env variable is indicating another, we need to either error or ignore the env variable?

To make more progress on deciding how to do this, we need to know more about what the environment variables will look like.     In #41 @janbartel will soon enumerated the various session configurations that we could deploy.  @meltsufin can you look at that issue and when you indicate which of those you want available on `jetty-runtime` can you also indicate how you imagine the environment variable will look like?  Will it be several booleans? an enumeration? will there be configuration env variables such as ports etc.?

**Comment by meltsufin** [comment]
I think your suggestion to preconfigure various modules in `gae.d/` and then move them into `start.d/` at runtime based on environment variables is a good compromise. I assume you intend this to be done only  for optional modules that we want to allow being enabled via environment variables. I would even just call the directory `opt.d/` or something similar to make it clear that these modules are not enabled by default. Required modules, on the other hand, can go directly into `start.d/`.

I'll comment on #41 regarding the environment variable names.

**Comment by gregw** [comment]
Having an `opt.d` for some modules still leaves us with two configuration mechanisms - either adding environment variables in `app.yaml` for modules that are supported, or adding commands/files in a dockerfile for modules that are not.

The problem I see with the app.yaml approach is that whilst setting an env variable to enable a module might be simple enough, there will inevitably be demand for configuration of the module or sub-options in the module.  This will lead to an explosion of env variables and a reworking of significant container configuration.

Wouldn't it be easier to just steer users to Dockerfile commands for configuration of modules?  A Dockerfile is not much more complex than `app.yaml`?

If we are to support env variables configuration in `app.yaml`, then I think we need a clear policy of what kind of things are suitable for `app.yaml` vs what kinds of things will require a Dockerfile, otherwise overtime I fear a piecemeal approach as arbitrary features are supported in `app.yaml`

**Comment by gregw** [comment]
Just doubling down on my comments in a different form.    I thought the idea that a user wants to use Flex  rather than standard GAE is so that they have the ability to configure the container.   So the expectation is that most users will eventually want to configure the container in fairly arbitrary ways.  If we wish to allow that without a Dockerfile, I think we are going to end up replicating large proportions of a container configuration in env variable, which are pretty much unsuitable for the task (else containers would just use them).

Surely we want some reasonable defaults behaviour in an image that is deployed without a Dockerfile (and I would assume that includes clustered session) and then leave all further customization to the Dockerfile - which is pretty easy to do with the new plugin.

**Comment by meltsufin** [comment]
@gregw I'm with you on not exposing module configuration through environment variables. That should be done by overwriting our default module settings files with a custom Dockerfile. Environment variables would only be used to turn on GCP-specific features, like clustered session management. In fact, currently, clustered session management and possibly application log redirection to Cloud Logging are the only two optional modules I can think of. I don't think we need to make any non-GCP-specific modules optional via environment variables.

**Comment by janbartel** [comment]
Might be nice if we could somehow leverage the new "--commands" mechanism ( #83 )  to allow users to provide properties that override the ones from the jetty base.

**Comment by gregw** [comment]
It indeed would be nice to be able to edit properties in ini files by command, but it would have to be a new feature as the --add-to-start mechanism on creates new ini files from a template.  We'd need something that visits all ini files... possible... thinking....

**Comment by gregw** [comment]
I've updated https://github.com/eclipse/jetty.project/issues/1139 to add a `--update-ini` option that allows properties to be set in existing ini files.  This will be in 9.4.0
