### ISSUE TITLE
Add /third_party/ for patched Spring Petclinic and Dandelion

### ISSUE THREAD

**Issue by joakime** [GoogleCloudPlatform/jetty-runtime#51]
Proposal to add the following to the repository:
- `/third_party/dandelion/` - which will be an initial import of HEAD of the `master` branch from https://github.com/dandelion/dandelion followed by the patch from PR dandelion/dandelion#116
- `/third_party/spring_petclinic/` - which will be an initial import of HEAD of the `master` branch from https://github.com/spring-projects/spring-petclinic followed by a patch to use the patched dandelion above

These 2 projects will be wired up into the maven build.

What should the groupId and artifactId be for those two new maven modules?

**Comment by joakime** [comment]
@meltsufin I can supply the PR for this, just let me know if the directory names and  proposed commits are ok.  

I propose the groupId be `com.google.cloud.runtime.jetty.third_party` and the artifactId's stay the same as the originals.
And if you have an opinion on the groupId / artitfactId

**Comment by meltsufin** [comment]
Your proposal sounds good for location and the group id. Thanks!

**Comment by joakime** [comment]
This can probably be closed, as it is no longer relevant.

Dandelion has been removed from spring-petclinic as part of issue https://github.com/spring-projects/spring-petclinic/issues/171
