### ISSUE TITLE
JMX Support

### ISSUE THREAD

**Issue by gregw** [GoogleCloudPlatform/jetty-runtime#6]
Jetty is fully instrumented with JMX mbeans that allow monitoring, control and debugging of the server. The JVM also provides useful information via JMX.

Should we provide modules and/or documentation to demonstrate how to enable JMX in the jetty-runtime and how to access it remotely.

**Comment by meltsufin** [comment]
We haven't tested it, but the JMX module should be automatically supported via the use of the `JETTY_MODULES_ENABLE` environment variable.
