### ISSUE TITLE
Ensure Jetty request logging doesn't fill up disk space

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/jetty-runtime#60]
Jetty request logging should either be completely turned off because request logging is already done by nginx proxy, or log rotation must be setup to limit the log file size on disk.

**Comment by joakime** [comment]
Implemented already as part of GoogleCloudPlatform/appengine-java-vm-runtime#231

**Comment by joakime** [comment]
This brings back up the need to introduce non-default logging to the Jetty image.

**Comment by meltsufin** [comment]
That was never merged into the old master. So, I reopened the issue there for a quick fix. In this repo, we're currently not writing Jetty logs to disk at all, right?

**Comment by joakime** [comment]
Nope, current master does not have "logging" module (which does the StdErr -> rotated files layer) 

https://github.com/GoogleCloudPlatform/jetty-runtime/blob/746eb6a590456b98accf451596cf0627462db6cb/jetty9-base/pom.xml#L138

**Comment by joakime** [comment]
Access logging from nginx is not integrated properly into the standard logging (there's no way yet to correlate the activity of a single request via its thread-id to the logs of the same thread-id at the same time).

Currently, the jetty produced access logging contains (logging) metadata about the thread that handled that request (useful for all non-async operations).

It will be appropriate to remove the jetty access logging layer when the following is satisfied:

1. When issue #4 is implemented and closed.
2. Google Cloud Logging integrates (at the server/console layer) the relationship between the request and all of its logs.

Only then, will removing the jetty access logs be appropriate.
(This should be a separate issue, not tied up this issue)

**Comment by joakime** [comment]
Also of note regarding question about "currently not writing Jetty logs to disk".

The `gae.mod` and associated other modules don't seem to pull in the `requestlog` or `logging` modules via transitive dependencies too.

The jetty-base seems to be producing no access/request logs at all, and only STDERR output on default logging at INFO level.

**Comment by joakime** [comment]
Ah, the [`gae.xml` adds the request logging manually](https://github.com/GoogleCloudPlatform/jetty-runtime/blob/8500b2e34cd6dc00718569d73209a23cce326273/jetty9-base/src/main/jetty-base/etc/gae.xml#L36-L48). (why are we not using the shipping `requestlog` module instead?)

**Comment by meltsufin** [comment]
I don't think this gets activated. @gregw Is this something we missed as part of #19?

**Comment by gregw** [comment]
@meltsufin the gae module does still get activated.    It includes a mostly default version of the request-log simply because it did before in the version of compat we inherited.

I don't think it is pre-empting our work on the design document too much to guess that a local request log is not needed in general (and easy to add if needed specifically).

Unless I hear otherwise I'll do a PR to remove the request log.

**Comment by meltsufin** [comment]
Agreed. I created an issue for removing the request logging and assigned it to you. #62

**Comment by gregw** [comment]
obsoleted by #68
