### ISSUE TITLE
Review test approaches

### ISSUE THREAD

**Issue by jmcc0nn3ll** [GoogleCloudPlatform/jetty-runtime#72]
I have pushed up a couple of branches, jcm-test-split and jcm-test-combined.

Briefly, the idea is to support both local and remote style of testing, the local using a local docker setup and the remote were a docker image is created and run using flex.

By default, no tests are run.

> cd tests;
> mvn install -Plocal -Djetty.test.image=jetty:9.3

This will run local tests using a locally installed jetty:9.3 image as the FROM line for the docker file.

> cd tests;
> mvn install -Premote -Djetty.test.image=gcr.io/<project>/jetty9:9.3

This will run remote tests using the appropriate remote image via cloud builder and run the tests.

Both branches follow the same basic command line approach.  However the split one has both 'local' and 'remote' container directories.  The combined one I like a bit more since it follows the model that jetty uses for our session tests where we can have the same basic test for multiple session managers and just implement them where we need, in this simple example we have a Hello world test with both a local and remote implementation.

@meltsufin thoughts?

**Comment by meltsufin** [comment]
@jmcc0nn3ll I like the combine approached more as well. There is a lot less code duplication that way.

**Comment by jmcc0nn3ll** [comment]
ok, I'll drill down on that, clean up for checkstyle, and submit a PR for it

**Comment by jmcc0nn3ll** [comment]
this has been resolved now
