### ISSUE TITLE
docker entrypoint for jetty uses ls in test.

### ISSUE THREAD

**Issue by gregw** [GoogleCloudPlatform/jetty-runtime#73]
the ls in the entrypoint script fails (as expected), but generates stderr log entries like:
```
7:05:40.000
17:05:40.000
OpenJDK 64-Bit Server VM (build 25.111-b14, mixed mode)
17:05:40.000
OpenJDK Runtime Environment (build 1.8.0_111-8u111-b14-2~bpo8+1-b14)
17:05:40.000
openjdk version "1.8.0_111"
17:05:40.000
ls: cannot access /var/lib/jetty/webapps/root: No such file or directory
17:05:39.000
17:05:39.000
OpenJDK 64-Bit Server VM (build 25.111-b14, mixed mode)
17:05:39.000
OpenJDK Runtime Environment (build 1.8.0_111-8u111-b14-2~bpo8+1-b14)
17:05:39.000
openjdk version "1.8.0_111"
17:05:38.000
ls: cannot access /var/lib/jetty/webapps/root: No such file or directory
```

**Comment by meltsufin** [comment]
@gregw Can you explain in what scenario this is happening? Is this only happening in a specific testing setup?

**Comment by gregw** [comment]
I did a `mvn appengine:deploy` on the `flexible/async-rest` example from `java-docs-samples` and the ls fails with that error message on every deploy.

The other option to this PR is to just `2>/dev/null` the ls, but I think an age check is more appropriate and is what jetty does internally anyway.
