### ISSUE TITLE
When app is missing a welcome file, directory listing is shown

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/jetty-runtime#88]
If the app doesn't have a file like index.jsp in the web root, a directory listing is shown.

```
Directory: /

META-INF/ 	4096 bytes 	Dec 7, 2016 10:42:46 AM
WEB-INF/ 	4096 bytes 	Dec 7, 2016 10:42:02 AM
```

This seems to be the default behavior of Jetty. Is this something we want to keep, or should we disable it if possible?

**Comment by jmcc0nn3ll** [comment]
DefaultServlet should be the one doing this and this behavior can be controlled through the _dirAllowed_ initparam

**Comment by meltsufin** [comment]
@gregw What do you think? What do other containers do?

**Comment by jmcc0nn3ll** [comment]
The standard Jetty behavior is to push our a listing of the contexts deployed, that dir listing you are talking about unless there is an index.html deployed.  

For this runtime scenario though I am inclined to say that less is more and we should 404 if nothing is there.

**Comment by WalkerWatch** [comment]
@meltsufin Per the call this evening - Tomcat controls this via the `listings` init param in the `web.xml`. By default it produces a 404 over listing the directory.

**Comment by meltsufin** [comment]
Thanks @WalkerWatch! I think we should have the same default then.

**Comment by gregw** [comment]
We change this behaviour in jetty by changing or replacing the default web.xml descriptor.     Currently we are deploying with a totally standard `webdefault.xml`.    I'm not sure this behaviour is significant enough to warrant making a change away from a totally standard distribution... unless we want to do so as an exemplar of how to change the `webdefault.xml`.

**Comment by jmcc0nn3ll** [comment]
We can wire that up through the gae.mod file right?

**Comment by gregw** [comment]
@jmcc0nn3ll sure, it's easy enough to do.  We add a new `defaultweb.xml` to the etc directory and we use the `gae-web.xml` to set a defaults descriptor on the context.

Only down side is that any changes to a released `defaultweb.xml` would need to be manually copied over, or perhaps we can do an extract and edit of the standard one in the pom?

**Comment by jmcc0nn3ll** [comment]
i suspect changes to the default one in jetty should trigger a review within this context anyway so might just be good policy to have it specified here since there is a change in default behavior here anyway

**Comment by gregw** [comment]
@joakime Good idea.  I'll do a PR for that.
