### ISSUE TITLE
Deprecated usage of --add-to-startd

### ISSUE THREAD

**Issue by jmcc0nn3ll** [GoogleCloudPlatform/jetty-runtime#95]
Running build on master shows the following WARN message in the logs.

Step 14 : RUN java -jar $JETTY_HOME/start.jar --add-to-startd=setuid  && chown -R jetty:jetty $JETTY_BASE  && mkdir /tmp/jetty && chown -R jetty:jetty /tmp/jetty  && ln -s $JETTY_BASE/webapps/root /app
 ---> Running in 3605e3788673
WARN  : --add-to-startd is deprecated! Instead use: --create-startd --add-to-start=setuid

INFO  : setuid          initialized in ${jetty.base}/start.d/setuid.ini

MKDIR : ${jetty.base}/resources

MKDIR : ${jetty.base}/webapps

INFO  :
Base directory was modified

 ---> c2861cd81292

**Comment by meltsufin** [comment]
I noticed this too! Is the fix as simple as adding `--create-startd` to the command?

**Comment by jmcc0nn3ll** [comment]
two small tweaks is all, we cleaned up this behavior in Jetty 9.4
